### ISSUE TITLE
Does not work on Linux

### ISSUE THREAD

**Issue by loredev10** [joelpt/quickfort#37]
Maybe I am missing something, but when I try to run qfconvert.py , I get an error.
I'm running that from the same directory, but it can't seem to find additional py libraries.

`Traceback (most recent call last):
  File "qfconvert.py", line 11, in <module>
    import blueprint
  File "/media/username/storage/DF/MasterworkDF_V5.06/quickfort/src/qfconvert/blueprint.py", line 8, in <module>
    import buildconfig
  File "/media/username/storage/DF/MasterworkDF_V5.06/quickfort/src/qfconvert/buildconfig.py", line 5, in <module>
    from filereader import load_json
  File "/media/username/storage/DF/MasterworkDF_V5.06/quickfort/src/qfconvert/filereader.py", line 12, in <module>
    from grid import Grid, GridLayer
  File "/media/username/storage/DF/MasterworkDF_V5.06/quickfort/src/qfconvert/grid.py", line 3, in <module>
    import numpy
ImportError: No module named numpy
`

**Comment by epsilon-phase** [comment]
You need to install numpy
